// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyjoyiymvgopvbtonipc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5am95aXltdmdvcHZidG9uaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MjgzNjEsImV4cCI6MjA1MDUwNDM2MX0.RK3m1AV8UGpGeb4n5hzU7QO73iLV7mJTPzlAuXQ4UWY";

// Create a single supabase client for interacting with your database
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false
  }
});

// For app directory server components
export async function getServerSupabase() {
  if (typeof window === 'undefined') {
    const { cookies } = await import('next/headers');
    const cookieStore = cookies();
  }
  return supabase;
}